### ISSUE TITLE
Linting failure in GitHub after passing pre-commit validation locally

### ISSUE THREAD

**Issue by amyminiter** [populationgenomics/tob-wgs#176]
My most recent push to `tob-wgs` passed pre-commit checks on my local machine, but failed when pushed to GitHub.

[Link to CI stack trace](https://github.com/populationgenomics/tob-wgs/actions/runs/9202860042/job/25313369772?pr=175).

`Downloading pycparser-2.22-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.6/117.6 kB 27.7 MB/s eta 0:00:00
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 c0f1f3ae52406a13eecb44ebe445be7d677d2c3b4e4e29269ecb53b7ac55168e
             Got        a29f5c6a0616f81eeb611882f5375b662cf9227[450](https://github.com/populationgenomics/tob-wgs/actions/runs/9202860042/job/25313369772?pr=175#step:4:451)07e7806133cf7d3786ba4a`

**Comment by amyminiter** [comment]
@dancoates I've tagged you randomly because I don't know who else to tag! Feel free to pass on to a more appropriate colleague.

**Comment by dancoates** [comment]
Huh, that's weird, I might just try re-running the job

**Comment by dancoates** [comment]
Ran fine on re-run - must be something slightly non-deterministic in one of the wheel builds, or a network error during install. Not too much to worry about unless it happens often. I'll close this but feel free to re-open if you run into it again

**Comment by jmarshall** [comment]
Yes, we see this very occasionally and theorise that it's a transient network error fetching the package.
