### ISSUE TITLE
Concordance of SNPchip with WGS calls

### ISSUE THREAD

**Issue by pdiakumis** [populationgenomics/tob-wgs#4]
* SNPchip VCF has SNP calls from GRCh37 and contains 1,034 samples and 483,482 variants. Example sample names are:

```
1) 1_1
2) 2_2
...

155) 163_163
156) 164_165 # <- right value starts being +1
157) 165_166
...
1029) 1084_1085
1030) 1096_845_2 <- dups start (845_846 exists) 
1031) 1100_914_2
1032) 1102_932_2
1033) 1103_926_2
1034) 1104_920_2
```

* WGS GVCFs are per-sample and contain >24 million ~~variants~~ rows each. Example sample names are:

```
TOB1524, TOB1532, TOB1533, ...
```

- [x] Get sample name mapping between platforms
- [x] Use Crossmap to liftover SNPchip VCF from GRCh37 to GRCh38
- [x] Filter out non-variant sites from GVCFs
- [x] Explore Hail Concordance, Picard GenotypeConcordance, custom solution

**Comment by lgruen** [comment]
>  Use Crossmap to liftover SNPchip VCF from GRCh37 to GRCh38

Would there be an advantage of reprocessing the raw data with GRCh38 instead of lifting over?

**Comment by pdiakumis** [comment]
Thought of that too. I guess we'll get a small percentage of variants that can't be lifted over (will try in a bit).
For reprocessing, we would need to figure out how/where to run GenomeStudio - I think it only runs on Windows (maybe we could grab a GCP Windows machine??).

**Comment by pdiakumis** [comment]
* Sort and convert GRCh37 to hg19

```shell
INPUT_VCF="onek1k_pre_imputation_genotypes.vcf.bgz"
OUTPUT_VCF="sorted_test.vcf.gz"

cat \
  <(bcftools view -h $INPUT_VCF | sed 's/contig=<ID=/contig=<ID=chr/') \
  <(bcftools view -H $INPUT_VCF | sort -k1n,1 -k2n,2 | awk '{{ print "chr" $0 }}' ) \
  | bgzip > $OUTPUT_VCF
```

* Liftover hg19 to hg38

```text
$ CrossMap.py vcf hg19ToHg38.over.chain.gz sorted_test.vcf.gz Homo_sapiens_assembly38.fasta sorted_test_hg38.vcf.gz
@ 2021-04-12 19:17:50: Read the chain file:  hg19ToHg38.over.chain.gz
@ 2021-04-12 19:17:51: Filter out variants [reference_allele == alternative_allele] ...
@ 2021-04-12 19:17:51: Updating contig field ...
@ 2021-04-12 19:17:51: Lifting over ...
@ 2021-04-12 19:18:20: Total entries: 483482
@ 2021-04-12 19:18:20: Failed to map: 910
```

**Comment by pdiakumis** [comment]
For filtering non-variant sites from single-sample GVCFs, we can use [gvcftools](https://github.com/sequencing/gvcftools) (an oldie from Chris Saunders from Illumina, but still works at least via [quay biocontainers](https://quay.io/repository/biocontainers/gvcftools)):

```
$ bcftools view -H TOB1524.g.vcf.gz | wc -l
 25,072,270
 
$ docker container run -v $(pwd):/data/ -it quay.io/biocontainers/gvcftools:0.17.0--he941832_3
$$ gzip -dc TOB1524.g.vcf.gz | extract_variants | gzip -c > TOB1524_extract_variants.vcf.gz
 
$ bcftools view -H TOB1524_extract_variants.vcf.gz | wc -l
 5,078,667
```

**Comment by pdiakumis** [comment]
Some concordance stats from three of the samples in the test bucket - I intentionally mixed up two samples to see what it looks like:

<img width="1019" alt="concordance_stats_2021-Apr-22" src="https://user-images.githubusercontent.com/29562861/115576724-1eb1cf00-a307-11eb-9bbb-b9824df4bce6.png">

Note that I'm only looking at chr, pos, and genotype for matches. The mismatches are mostly due to e.g. `0/2` vs `0/1`, `1/0` vs. `0/1` etc.
