### ISSUE TITLE
scRNA-seq SNV calling

### ISSUE THREAD

**Issue by pdiakumis** [populationgenomics/tob-wgs#60]
From discussion with Kat:

- Monovar + GATK: [SNV identification from single-cell RNA sequencing data](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7279618/)
- Red panda: [Red panda: a novel method for detecting variants in single-cell RNA sequencing](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-020-07224-3)

**Comment by KatalinaBobowik** [comment]
Isn't Monovar a separate pipeline from GATK? I think we should prioritise GATK and see what the differences are in using RNA-seq data versus a regular DNA pipeline, followed by Monovar as a second choice.

**Comment by pdiakumis** [comment]
Yep, that paper compares the two pipelines, just keeping notes down ;-)
And yep, agree with prioritising GATK.

**Comment by KatalinaBobowik** [comment]
Nice, I think we just need to figure out how exactly to call variants with RNA-seq (with for example, a GATK pipeline), so those papers will be a good resource. I can dig into that

**Comment by pdiakumis** [comment]
Closing as this will be handled outside CPG.
